### ISSUE TITLE
As of today it doesn't work because of "Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found"

### ISSUE THREAD

**Issue by NinjaTurtle007** [nlpsuge/gnome-shell-extension-another-window-session-manager#69] opened 2023-02-08 16:30 UTC
I think it was due to update after restart yesterday and today it doesn't start with this message in the Extensions app. Removing and adding it doesn't help.

**Comment by Whats-the-time** [comment] 2023-02-08 19:05
Same issue here after update on Pop!_OS 22.04 today.

**Comment by Whats-the-time** [comment] 2023-02-08 19:17
Installing gir1.2-gtop-2.0 seemed to fix it for me.

**Comment by NinjaTurtle007** [comment] 2023-02-08 19:54
seems to fix it for me also, thanks @Whats-the-time !

**Comment by curiousercreative** [comment] 2023-02-09 16:55
Just to say that my Pop! 22.04 systems also reproduce this issue.

**Comment by noweasyjay** [comment] 2023-02-09 19:54
typelib-1_0-GTop-2_0 works for opensuse

**Comment by nashamri** [comment] 2023-02-09 20:01
This fixes it for me if you are using NixOS:
`services.xserver.desktopManager.gnome.sessionPath = [ pkgs.libgtop ];`

**Comment by beardChamp** [comment] 2023-03-14 17:13
> Installing gir1.2-gtop-2.0 seemed to fix it for me.

Installing this resolved my issues on Ubuntu 22.04

**Comment by RemcoSchrijver** [comment] 2023-03-22 14:39
Maybe add this as instructions for dependencies on debian based systems in the readme?

**Comment by nlpsuge** [comment] 2023-03-22 16:34
@RemcoSchrijver 

I just merged a PR which describes this dependency and installation instructions, you can find it here:

https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager#dependencies

But I'm mainly using Fedora daily, welcome to complete it.

**Comment by RemcoSchrijver** [comment] 2023-03-23 09:11
@nlpsuge 
Yeah lgtm, added a small change that removed the Pop!_OS reference in #76 because it is a Ubuntu derivative anyway so the same installation methods should work. Think with that this issue can be closed?

**Comment by nlpsuge** [comment] 2023-03-23 13:52
@RemcoSchrijver 

https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/pull/76 has been merged to main branch, I close this issue then.

**Closed by nlpsuge** 2023-03-23 13:52 UTC
