### ISSUE TITLE
Display awareness

### ISSUE THREAD

**Issue by koriwi** [nlpsuge/gnome-shell-extension-another-window-session-manager#21] opened 2022-01-06 09:48 UTC
Hi
Thanks for your awesome work :)
I really want to use this extension but i got really confused in the first place because all my applications got opened on my left screen (FYI my right is my primary) and they stacked, so it looked like half my apps were missing.

Maybe you aren't aware of this because you are only using one screen and did not see an issue for this. So here it is.

**Comment by koriwi** [comment] 2022-01-06 09:50
Just found this in the gnome-shell-extension comments:

> Currently, it does not support multiple monitors. I don't have more monitors to test it either.
I will add this support in the future.

**Comment by nlpsuge** [comment] 2022-01-06 10:34
> and they stacked

In which workspace on your left screen they stacked? The first workspace?

**Comment by nlpsuge** [comment] 2022-01-06 13:18
@koriwi 
I suggest you watch the logs to see if report any relevant errors via `journalctl /usr/bin/gnome-shell -f` when reproduce.

Note you may need to run `journalctl /usr/bin/gnome-shell -f` under root.

**Comment by nlpsuge** [comment] 2022-01-11 07:50
@koriwi 

A new version which supports dual monitors will be approved today or tomorrow. 

BTW, are you running Gnome on X11 or Wayland? I only test it on X11, but expect it works on Wayland too. I can't test on Wayland due to the hardware limitation.

----
P.S.
Thanks to https://github.com/kbumsik/VirtScreen, I managed to create a virtual second monitor, so I can develop and test.

**Comment by koriwi** [comment] 2022-01-11 08:42
Very nice! Thank you very much. Will test after work

**Comment by nlpsuge** [comment] 2022-01-11 09:15
> Very nice! Thank you very much. Will test after work

Please test it using source code:
```sh
cd /tmp
git clone https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager.git
cp -rp gnome-shell-extension-another-window-session-manager/* ~/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/
```
Then restart gnome shell using `alt+f2 type r` if on X11 or logout and login if On Wayland.

Thanks. :)

**Comment by nlpsuge** [comment] 2022-01-11 13:11
@koriwi 

No need to test for now, I have to improve the code. :)

**Comment by nlpsuge** [comment] 2022-01-18 09:49
Hi @koriwi, 

A new release has been approved,  and it supports multi-monitor.

I only tested it on X11, but I expect it works on Wayland.

Feedback is welcome. :)

**Comment by koriwi** [comment] 2022-01-18 10:02
I will try it after work!

**Comment by nlpsuge** [comment] 2022-07-11 15:29
Close this issue now, please reopen it if it still has issue there.

**Closed by nlpsuge** 2022-07-11 15:29 UTC
Labels: enhancement, help wanted, multi-monitor
