### ISSUE TITLE
Problem in multi-monitor mode with two horizontal rows of screens

### ISSUE THREAD

**Issue by RebelSon84** [nlpsuge/gnome-shell-extension-another-window-session-manager#63] opened 2022-11-15 15:55 UTC
Hello!
There is a problem with moving windows to the top row of monitors (monitor 1 in the screenshot)

As far as I understand, this is due to the fact that the origin point for windows "x_offset": 0, "y_offset": 0,  is the upper left corner of monitor 2.

I can move windows horizontally using "x_offset" in the config file.
But I can't raise the window vertically because "y_offset": 0 this is the highest point of the monitors 2 and 3.

Perhaps using negative "y_offset" values could help, but it didn't work for me.

![Screenshot from 2022-11-15 18-35-51](https://user-images.githubusercontent.com/103286405/201961023-1a5d4dec-9395-4b06-a2dd-948f80d76a9b.png)

**Comment by RebelSon84** [comment] 2022-11-15 16:01
I use Manjaro Linux 22.0.0 with GNOME Shell 42.5

**Comment by nlpsuge** [comment] 2022-11-16 15:04
What is the `x_offset`, `y_offset` of the app in the monitor 1? Please show me the `window_position` part in the session file related to this app.

Can you move the app from monitor 2 to monitor 1 by hand?

**Comment by nlpsuge** [comment] 2022-11-17 14:35
Look somehow the app just falls on the primary monitor. 

I'm not sure why, but we probably can find some clue in the logs. 

First, please enable the `Debugging mode` in the extension Settings:
![image](https://user-images.githubusercontent.com/2271720/202470215-3a85288e-3462-4302-913a-caa968a016c3.png)

Second, watch the logs in the terminal via  `journalctl -o short-precise -r /usr/bin/{gjs,gjs-console,gnome-shell}` .

Third, reproduce the above steps again and there should be some logs, like `Moving gedit - a title to the primary monitor x from y`.

I don't even have a physical monitor, I can't test this issue properly. :(

----

Related code:
https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/blob/0c19c020cbb5353a53ecdc69ed966807eb93ecfa/moveSession.js#L114-L177

**Comment by nlpsuge** [comment] 2022-11-17 16:44
This is a bug.

Related code:
https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/blob/0c19c020cbb5353a53ecdc69ed966807eb93ecfa/moveSession.js#L81-L82


L81 does move the window to the monitor that it's supposed to be in. But L82 moves it to the primary monitor while L82 restores the size and geometry using `metaWindow.move_resize_frame` .

I'll fix it later.

**Comment by nlpsuge** [comment] 2022-11-18 14:46
@RebelSon84 
Hi, did you have this issue on the older GNOME Shells?

**Comment by nlpsuge** [comment] 2022-11-19 04:41
This issue had been committed to https://gitlab.gnome.org/GNOME/mutter/-/issues/2340 4 months ago.

**Comment by RebelSon84** [comment] 2022-11-19 17:52
> did you have this issue on the older GNOME Shells?
Hello!
I'll check it out.
But I didn't seem to notice it before.

**Comment by nlpsuge** [comment] 2022-11-21 14:31
Looks like it's a bug of mutter and have reported it: https://gitlab.gnome.org/GNOME/mutter/-/issues/2521

**Comment by nlpsuge** [comment] 2022-11-22 16:03
@RebelSon84 

Hi, could you please test this branch https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/compare/bugfix-multi-monitor?

You can download it from the release page: https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/releases/tag/29.1 

After downloading, copy the contents to extension folder: 
`cp -rp gnome-shell-extension-another-window-session-manager-29.1/* ~/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/

Then restart gnome shell (using `alt+f2 type r`  for X11 or logout and login for Wayland).

`

**Comment by RebelSon84** [comment] 2022-11-22 21:06
>Hi, could you please test this branch

Hello!
Everything works great!
Thank you very much

**Closed** 2022-11-22 21:06 UTC
Labels: bug, multi-monitor
